name: Make TWRP Device from URL

on:
  workflow_dispatch:
    inputs:
      IMAGE_URL:
        description: Direct URL of your image
        required: true
      OUTPUT_PATH:
        description: Output device tree path
        required: false
        default: dt

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download boot or recovery image
      run: |
        curl "${{ github.event.inputs.IMAGE_URL }}" -o build.img
    - name: Check downloaded images
      run: |
        ls -alh *.img
    - name: Start building
      id: build
      uses: ./.github/actions/build-device-tree
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: ${{ github.event.inputs.OUTPUT_PATH }}
        name: TWRP_Device_Tree-${{ github.run_id }}
